### ISSUE TITLE
collection.count is deprecated

### ISSUE THREAD

**Issue by abea** [apostrophecms/emulate-mongo-2-driver#6]
>  (node:34154) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead

With the current updates I'm still getting this one deprecation warning. We should emulate it as well.

**Comment by boutell** [comment]
Yep. We need to do our homework and figure out which method it is equivalent to. It might actually have been potentially not quite accurate (like estimatedDocumentCount) all along.

**Comment by boutell** [comment]
The one doesn't take a query so that's right out. The other has a change in syntax from count that will have to be taken into *cough* account:

http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#countDocuments
